import Head from 'next/head';
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'
import { Grid } from '@mui/material';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        {/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <Grid>aaa</Grid>
    </>
  );
}
